name: Checkov

on:
  push:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Checkov on testing-co
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./testing-co
          framework: terraform
          download_external_modules: true
          skip_check: CKV2_AWS_5