name: Checkov

on:
  push:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Checkov and export to TXT
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./testing-co
          framework: terraform
          download_external_modules: true
          skip_check: CKV2_AWS_5
          output_format: cli
          output_file_path: ./testing-co/checkov-results.txt

      - name: Upload TXT report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: checkov-results-txt
          path: ./testing-co/checkov-results.txt